pipeline {
    agent any

    tools {
        jdk 'Java17'        // Make sure JDK17 is configured in Jenkins
        maven 'Maven3'      // Make sure Maven3 is configured in Jenkins
    }

    environment {
        REPORT_DIR = 'target/surefire-reports'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Abimanyurm/QA-Automation-Scripts.git', credentialsId: 'github-new-token'
            }
        }

        stage('Build & Test') {
            steps {
                // Navigate to the folder containing pom.xml
                dir('API-Automation/RestAssured-Scripts/ssoscripts/api-automation') {
                    bat 'mvn clean compile'
                    bat 'mvn test'
                }
            }
        }

        stage('Publish Report') {
            steps {
                dir('API-Automation/RestAssured-Scripts/ssoscripts/api-automation') {
                    junit "${env.REPORT_DIR}/*.xml"
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'API-Automation/RestAssured-Scripts/ssoscripts/api-automation/target/*.jar', allowEmptyArchive: true
        }
    }
}
