pipeline {
    agent any

    tools {
        jdk 'Java17' // Your configured JDK in Jenkins
        maven 'Maven3' // Your configured Maven in Jenkins
    }

    environment {
        REPORT_DIR = 'target/surefire-reports'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Abimanyurm/QA-Automation-Scripts.git', credentialsId: 'github-new-token'
            }
        }

        stage('Build') {
            steps {
                dir('API-Automation') { // Go into the folder where pom.xml exists
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('API-Automation') {
                    bat 'mvn test'
                }
            }
        }

        stage('Publish Report') {
            steps {
                dir('API-Automation') {
                    junit "${env.REPORT_DIR}/*.xml"
                }
            }
        }
    }

    post {
        always {
            dir('API-Automation') {
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
        success {
            echo '✅ Build and Tests succeeded!'
        }
        failure {
            echo '❌ Build or Tests failed!'
        }
    }
}
